INSERT INTO card_table (NAME, MANA_COST, CMC, TYPE_LINE, ORACLE_TEXT, POWER, TOUGHNESS, COLORS, COLOR_ID, SETIF, RARITY) VALUES
( 'Angelic Exaltation',
  '{3}{W}',
  4,
  'Enchantment',
  'Whenever a creature you control attacks alone, it gets +X/+X until end of turn, where X is the number of creatures you control.',
  null,
  null,
  ( 'W' ),
  ( 'W' ),
  'rna',
  'uncommon' ),
( 'Archway Angel',
  '{5}{W}',
  6,
  'Creature — Angel',
  'Flying When Archway Angel enters the battlefield, you gain 2 life for each Gate you control.',
  '3',
  '4',
  ( 'W' ),
  ( 'W' ),
  'rna',
  'uncommon' ),
( 'Arresters Zeal',
  '{W}',
  1,
  'Instant',
  'Target creature gets +2/+2 until end of turn. Addendum — If you cast this spell during your main phase, that creature gains flying until end of turn.',
  null,
  null,
  ( 'W' ),
  ( 'W' ),
  'rna',
  'common' ),
( 'Bring to Trial',
  '{2}{W}',
  3,
  'Sorcery',
  'Exile target creature with power 4 or greater.',
  null,
  null,
  ( 'W' ),
  ( 'W' ),
  'rna',
  'common' ),
( 'Civic Stalwart',
  '{3}{W}',
  4,
  'Creature — Elephant Soldier',
  'When Civic Stalwart enters the battlefield, creatures you control get +1/+1 until end of turn.',
  '3',
  '3',
  ( 'W' ),
  ( 'W' ),
  'rna',
  'common' ),
( 'Concordia Pegasus',
  '{1}{W}',
  2,
  'Creature — Pegasus',
  'Flying',
  '1',
  '3',
  ( 'W' ),
  ( 'W' ),
  'rna',
  'common' )